--
-- PostgreSQL database dump
--

\restrict nQ2Z306UhD6SLPNQwTrrf0ReYbckqy1NPRZ9mAeSwbxrIfUTRMANbSNRiflbIiq

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: chinwag; Type: SCHEMA; Schema: -; Owner: hbar1st
--

CREATE SCHEMA chinwag;


ALTER SCHEMA chinwag OWNER TO hbar1st;

--
-- Name: reaction; Type: TYPE; Schema: chinwag; Owner: hbar1st
--

CREATE TYPE chinwag.reaction AS ENUM (
    'thumbs_up',
    'cry',
    'love',
    'laugh',
    'strong',
    'celebrate'
);


ALTER TYPE chinwag.reaction OWNER TO hbar1st;

--
-- Name: t_username; Type: DOMAIN; Schema: chinwag; Owner: hbar1st
--

CREATE DOMAIN chinwag.t_username AS character varying(32)
	CONSTRAINT t_username_check CHECK (((length((VALUE)::text) >= 1) AND (length((VALUE)::text) <= 32)));


ALTER DOMAIN chinwag.t_username OWNER TO hbar1st;

--
-- Name: getunreadmsgcounts(integer); Type: FUNCTION; Schema: chinwag; Owner: hbar1st
--

CREATE FUNCTION chinwag.getunreadmsgcounts(iuserid integer) RETURNS TABLE(chat_id integer, icon_id integer, descr text, count integer)
    LANGUAGE sql
    AS $$
  SELECT
    cm.chat_id,
    chats.icon_id,
    chats.descr,
    COUNT(mm.message_id) AS count
  FROM chinwag.chat_members AS cm
  JOIN chinwag.chats AS chats
    ON chats.id = cm.chat_id
  LEFT JOIN chinwag.messages AS msgs
    ON msgs.chat_id = cm.chat_id
  LEFT JOIN chinwag.messages_meta AS mm
    ON mm.message_id = msgs.id
   AND mm.recipient_id = iUserId
   AND mm.read_at IS NULL
  WHERE cm.user_id = iUserId
    AND cm.has_left = FALSE
  GROUP BY cm.chat_id, chats.icon_id, chats.descr
  ORDER BY cm.chat_id;
$$;


ALTER FUNCTION chinwag.getunreadmsgcounts(iuserid integer) OWNER TO hbar1st;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.activity (
    user_id integer NOT NULL,
    last_active timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE chinwag.activity OWNER TO hbar1st;

--
-- Name: chat_admins; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.chat_admins (
    chat_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE chinwag.chat_admins OWNER TO hbar1st;

--
-- Name: chat_members; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.chat_members (
    id integer NOT NULL,
    chat_id integer NOT NULL,
    user_id integer NOT NULL,
    has_left boolean DEFAULT false
);


ALTER TABLE chinwag.chat_members OWNER TO hbar1st;

--
-- Name: chat_members_id_seq; Type: SEQUENCE; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE chinwag.chat_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chinwag.chat_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chats; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.chats (
    id integer NOT NULL,
    icon_id integer,
    name character varying(75) NOT NULL,
    descr character varying(125),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE chinwag.chats OWNER TO hbar1st;

--
-- Name: chats_id_seq; Type: SEQUENCE; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE chinwag.chats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chinwag.chats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: friends; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.friends (
    id integer NOT NULL,
    user_id_1 integer NOT NULL,
    user_id_2 integer NOT NULL
);


ALTER TABLE chinwag.friends OWNER TO hbar1st;

--
-- Name: friends_id_seq; Type: SEQUENCE; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE chinwag.friends ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chinwag.friends_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: images; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.images (
    id integer NOT NULL,
    img_url text NOT NULL,
    resource_type text NOT NULL,
    public_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE chinwag.images OWNER TO hbar1st;

--
-- Name: images_id_seq; Type: SEQUENCE; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE chinwag.images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chinwag.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_image; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.message_image (
    message_id integer NOT NULL,
    image_id integer NOT NULL
);


ALTER TABLE chinwag.message_image OWNER TO hbar1st;

--
-- Name: message_reactions; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.message_reactions (
    reaction chinwag.reaction NOT NULL,
    user_id integer NOT NULL,
    message_id integer NOT NULL
);


ALTER TABLE chinwag.message_reactions OWNER TO hbar1st;

--
-- Name: messages; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.messages (
    id integer NOT NULL,
    reply_to integer,
    content character varying(1000) NOT NULL,
    sent_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    deleted boolean DEFAULT false NOT NULL,
    chat_id integer NOT NULL,
    author_id integer NOT NULL
);


ALTER TABLE chinwag.messages OWNER TO hbar1st;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE chinwag.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chinwag.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages_meta; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.messages_meta (
    message_id integer NOT NULL,
    recipient_id integer NOT NULL,
    delivered_at timestamp with time zone,
    read_at timestamp with time zone
);


ALTER TABLE chinwag.messages_meta OWNER TO hbar1st;

--
-- Name: passwords; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.passwords (
    user_id integer NOT NULL,
    user_password character varying(64) NOT NULL
);


ALTER TABLE chinwag.passwords OWNER TO hbar1st;

--
-- Name: users; Type: TABLE; Schema: chinwag; Owner: hbar1st
--

CREATE TABLE chinwag.users (
    id integer NOT NULL,
    username chinwag.t_username NOT NULL,
    email text NOT NULL,
    nickname character varying(25) NOT NULL,
    avatar_id integer
);


ALTER TABLE chinwag.users OWNER TO hbar1st;

--
-- Name: user_profile; Type: VIEW; Schema: chinwag; Owner: hbar1st
--

CREATE VIEW chinwag.user_profile AS
 SELECT u.id,
    u.username,
    u.email,
    u.nickname,
    u.avatar_id,
    i.id AS image_id,
    i.img_url,
    i.resource_type,
    i.public_id
   FROM (chinwag.users u
     LEFT JOIN chinwag.images i ON ((u.avatar_id = i.id)));


ALTER VIEW chinwag.user_profile OWNER TO hbar1st;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE chinwag.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chinwag.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activity activity_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.activity
    ADD CONSTRAINT activity_pkey PRIMARY KEY (user_id);


--
-- Name: chat_admins chat_admins_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.chat_admins
    ADD CONSTRAINT chat_admins_pkey PRIMARY KEY (chat_id, user_id);


--
-- Name: chat_members chat_members_chat_id_user_id_key; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.chat_members
    ADD CONSTRAINT chat_members_chat_id_user_id_key UNIQUE (chat_id, user_id);


--
-- Name: chat_members chat_members_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.chat_members
    ADD CONSTRAINT chat_members_pkey PRIMARY KEY (id);


--
-- Name: chats chats_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (id);


--
-- Name: friends friends_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.friends
    ADD CONSTRAINT friends_pkey PRIMARY KEY (id);


--
-- Name: friends friends_user_id_1_user_id_2_key; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.friends
    ADD CONSTRAINT friends_user_id_1_user_id_2_key UNIQUE (user_id_1, user_id_2);


--
-- Name: images images_img_url_key; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.images
    ADD CONSTRAINT images_img_url_key UNIQUE (img_url);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- Name: images images_public_id_key; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.images
    ADD CONSTRAINT images_public_id_key UNIQUE (public_id);


--
-- Name: message_image message_image_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.message_image
    ADD CONSTRAINT message_image_pkey PRIMARY KEY (message_id, image_id);


--
-- Name: message_reactions message_reactions_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.message_reactions
    ADD CONSTRAINT message_reactions_pkey PRIMARY KEY (user_id, message_id);


--
-- Name: messages_meta messages_meta_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.messages_meta
    ADD CONSTRAINT messages_meta_pkey PRIMARY KEY (message_id, recipient_id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: passwords passwords_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.passwords
    ADD CONSTRAINT passwords_pkey PRIMARY KEY (user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: activity activity_user_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.activity
    ADD CONSTRAINT activity_user_id_fkey FOREIGN KEY (user_id) REFERENCES chinwag.users(id) ON DELETE CASCADE;


--
-- Name: chat_admins chat_admins_chat_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.chat_admins
    ADD CONSTRAINT chat_admins_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES chinwag.chats(id) ON DELETE CASCADE;


--
-- Name: chat_admins chat_admins_user_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.chat_admins
    ADD CONSTRAINT chat_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES chinwag.users(id) ON DELETE CASCADE;


--
-- Name: chat_members chat_members_chat_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.chat_members
    ADD CONSTRAINT chat_members_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES chinwag.chats(id) ON DELETE CASCADE;


--
-- Name: chat_members chat_members_user_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.chat_members
    ADD CONSTRAINT chat_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES chinwag.users(id) ON DELETE CASCADE;


--
-- Name: chats chats_icon_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.chats
    ADD CONSTRAINT chats_icon_id_fkey FOREIGN KEY (icon_id) REFERENCES chinwag.images(id) ON DELETE RESTRICT;


--
-- Name: friends friends_user_id_1_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.friends
    ADD CONSTRAINT friends_user_id_1_fkey FOREIGN KEY (user_id_1) REFERENCES chinwag.users(id) ON DELETE CASCADE;


--
-- Name: friends friends_user_id_2_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.friends
    ADD CONSTRAINT friends_user_id_2_fkey FOREIGN KEY (user_id_2) REFERENCES chinwag.users(id) ON DELETE CASCADE;


--
-- Name: message_image message_image_image_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.message_image
    ADD CONSTRAINT message_image_image_id_fkey FOREIGN KEY (image_id) REFERENCES chinwag.images(id) ON DELETE RESTRICT;


--
-- Name: message_image message_image_message_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.message_image
    ADD CONSTRAINT message_image_message_id_fkey FOREIGN KEY (message_id) REFERENCES chinwag.messages(id) ON DELETE RESTRICT;


--
-- Name: message_reactions message_reactions_message_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.message_reactions
    ADD CONSTRAINT message_reactions_message_id_fkey FOREIGN KEY (message_id) REFERENCES chinwag.messages(id) ON DELETE CASCADE;


--
-- Name: message_reactions message_reactions_user_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.message_reactions
    ADD CONSTRAINT message_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES chinwag.users(id) ON DELETE CASCADE;


--
-- Name: messages messages_author_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.messages
    ADD CONSTRAINT messages_author_id_fkey FOREIGN KEY (author_id) REFERENCES chinwag.users(id) ON DELETE CASCADE;


--
-- Name: messages messages_chat_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.messages
    ADD CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES chinwag.chats(id) ON DELETE CASCADE;


--
-- Name: messages_meta messages_meta_message_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.messages_meta
    ADD CONSTRAINT messages_meta_message_id_fkey FOREIGN KEY (message_id) REFERENCES chinwag.messages(id) ON DELETE CASCADE;


--
-- Name: messages_meta messages_meta_recipient_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.messages_meta
    ADD CONSTRAINT messages_meta_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES chinwag.users(id) ON DELETE CASCADE;


--
-- Name: messages messages_reply_to_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.messages
    ADD CONSTRAINT messages_reply_to_fkey FOREIGN KEY (reply_to) REFERENCES chinwag.messages(id);


--
-- Name: passwords passwords_user_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.passwords
    ADD CONSTRAINT passwords_user_id_fkey FOREIGN KEY (user_id) REFERENCES chinwag.users(id) ON DELETE CASCADE;


--
-- Name: users users_avatar_id_fkey; Type: FK CONSTRAINT; Schema: chinwag; Owner: hbar1st
--

ALTER TABLE ONLY chinwag.users
    ADD CONSTRAINT users_avatar_id_fkey FOREIGN KEY (avatar_id) REFERENCES chinwag.images(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict nQ2Z306UhD6SLPNQwTrrf0ReYbckqy1NPRZ9mAeSwbxrIfUTRMANbSNRiflbIiq

