
DROP SCHEMA IF EXISTS chinwag CASCADE;
CREATE SCHEMA chinwag;

CREATE DOMAIN chinwag.t_username AS varchar(32)
CHECK (
  length(VALUE) BETWEEN 1 AND 32
);

CREATE TABLE chinwag.users ( 
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  username chinwag.t_username NOT NULL UNIQUE, 
  email varchar(70) UNIQUE,
  nickname varchar(25) NOT NULL,
  avatar_url text,
  last_active timestamptz NOT NULL,

  UNIQUE (id, email)
);

CREATE TABLE chinwag.passwords (
  user_id integer PRIMARY KEY REFERENCES chinwag.users(id), 
  user_password varchar(64) NOT NULL
);


CREATE TYPE chinwag.reaction AS ENUM (
  'thumbs_up',
  'cry',
  'love',
  'laugh',
  'strong',
  'celebrate'
);

CREATE TABLE chinwag.friends (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id_1 integer NOT NULL REFERENCES chinwag.users(id),
  user_id_2 integer NOT NULL REFERENCES chinwag.users(id),
  UNIQUE (user_id_1, user_id_2)
);


CREATE TABLE chinwag.chats (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon_url text,
  name varchar(75) NOT NULL,
  descr text,
  created_at timestamptz NOT NULL DEFAULT (now()),
  updated_at timestamptz
);

CREATE TABLE chinwag.chat_members (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id integer NOT NULL REFERENCES chinwag.chats(id),
  user_id integer NOT NULL REFERENCES chinwag.users(id),

  UNIQUE(chat_id,user_id)
);


CREATE TABLE chinwag.messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reply_to integer REFERENCES chinwag.messages(id),
  content varchar(1000) NOT NULL,
  sent_at timestamptz NOT NULL DEFAULT (now()),
  delivered_at timestamptz,
  updated_at timestamptz,
  read_at timestamptz,
  deleted boolean NOT NULL DEFAULT FALSE,
  chat_id integer NOT NULL REFERENCES chinwag.chats(id),
  author_id integer NOT NULL REFERENCES chinwag.users(id)
);

CREATE TABLE chinwag.images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url text NOT NULL,
  message_id integer NOT NULL REFERENCES chinwag.messages(id),
  created_at timestamptz
);


CREATE TABLE chinwag.message_reaction (
  reaction chinwag.reaction NOT NULL,
  user_id integer NOT NULL REFERENCES chinwag.users(id),
  message_id integer NOT NULL REFERENCES chinwag.messages(id),
  PRIMARY KEY (user_id, message_id)
);